apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kub
  template:
    metadata:
      labels:
        app: kub
    spec:
      containers:
      - name: kub
        image: mcrawford19/kub:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kub-service
spec:
  type: NodePort
  selector:
    app: kub
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

